# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-16 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='employee_username',
            field=models.CharField(default='old', max_length=30),
        ),
    ]
